controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


home:
    path: /
    controller : 'App\Controller\AgrometalController::homepageController'

equipment:
    path: /equipment
    controller : 'App\Controller\AgrometalController::equipementsController'

references:
    path: /references
    controller : 'App\Controller\AgrometalController::referencesController'

contacts:
    path: /contacts
    controller : 'App\Controller\AgrometalController::contactsController'

adminpanel:
    path: /adminpanel
    controller : 'App\Controller\AgrometalController::adminpanelController'


    

